application: mtgotranslate
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /admin
  script: admin.py
  login: admin

- url: /.*
  script: upload.py

builtins:
- remote_api: on